# Generated by Django 3.0.3 on 2020-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='hi', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
