# Generated by Django 3.0.3 on 2020-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200917_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
