# Generated by Django 3.0.3 on 2020-09-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_header_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_pic',
            field=models.ImageField(null=True, upload_to='pictures'),
        ),
    ]
