# Generated by Django 3.0.3 on 2020-09-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_prj_or_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extract',
            field=models.CharField(default='Extract from post', max_length=300),
        ),
    ]
